config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :amazon_products, :only => [:create, :index]
    resources :amazon_imports, :only => [:create, :index, :new]
    resources :amazon_taxons, :only => [:index]

    resources :flipkart_products, :only => [:create, :index]
    resources :flipkart_imports, :only => [:create, :index, :new]
    resources :flipkart_taxons, :only => [:index,:flipkart_products]
    get 'flipkart_taxons/flipkart_products'
    get 'flipkart_products/search_products'

  end
  # get "/admin/flipkart_taxons/products_by_taxons","flipkart_taxons#products_by_taxons",:as=>'flipkart_products_by_taxons'

end

app/controllers/spree/admin/flipkart_taxons_controller.rb
class Spree::Admin::FlipkartTaxonsController < Spree::Admin::BaseController

  def index
    if params[:taxon_id]
      @taxons = Spree::Flipkart::Taxon.find(params[:taxon_id]).children
    else
      @taxons = Spree::Flipkart::Taxon.roots
    end
  end

  def flipkart_products

    if params[:taxon_id]
      p "==========conrtrrrprprprprprp"
     p rest_url = "https://affiliate-api.flipkart.net/affiliate/1.0/feeds/shivar547/category#{params[:taxon_id]}"

      @amazon_products = Spree::Flipkart::Product.find_tax(rest_url)
    end
  end

end

app/views/spree/admin/flipkart_taxons/flipkart_products.html.erb
<%= render :partial => 'spree/admin/shared/amazon_sub_menu' %>

<h1><%= t("flipkart_products") %></h1>

<table class="index">
  <thead data-hook="admin_amazon_products_index_headers">
  <th><%= t("image") %></th>
  <th><%= t("amazon_id") %></th>
  <th><%= t('price') %></th>
  <th><%= t("name") %></th>
  <th data-hook="admin_amazon_products_index_header_actions">&nbsp;</th>
  </thead>
  <tbody>
  <% @amazon_products.each do |product|%>
    <tr data-hook="admin_amazon_products_index_rows">
      <td><%= link_to image_tag(product.images.first.attachment.url), product.product_url, :alt => product.name, :target => '_blank' if product.images.first %></td>
      <td><%= product.id %></td>
      <td><%= product.price %></td>
      <td><%= link_to product.name.html_safe, product.product_url, :target => '_blank' %></td>
      <td><%= button_to t(:add_to_store), admin_amazon_products_path(:asin => product.id), :method => 'POST' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%#= paginate @amazon_products %>

<%= render :partial => 'spree/admin/shared/flipkart_product_search' %>

app/views/spree/admin/flipkart_taxons/index.html.erb
<%= render :partial => 'spree/admin/shared/amazon_sub_menu' %>

<h1><%= t("amazon_taxons") %></h1>

<table class="index">
  <thead data-hook="admin_amazon_index_headers">
    <th><%= t("name") %></th>
    <th data-hook="admin_amazon_index_header_actions">&nbsp;</th>
  </thead>
  <tbody>
    <% @taxons.each do |taxon|%>
      <tr data-hook="admin_amazon_index_rows">
        <td><%= taxon[:name] %></td>
        <td>
          <%#= link_to t(:child_taxons), admin_flipkart_taxons_path(:taxon_id => taxon[:name]) %>
<!--          |-->
          <%= link_to t(:view_products), admin_flipkart_products_search_products_path(:taxon_id => taxon[:taxon_url].split("category").last
          ) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render :partial => 'spree/admin/shared/flipkart_product_search' %>