config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :amazon_products, :only => [:create, :index]
    resources :amazon_imports, :only => [:create, :index, :new]
    resources :amazon_taxons, :only => [:index]

    resources :flipkart_products, :only => [:create, :index]
    resources :flipkart_imports, :only => [:create, :index, :new]
    resources :flipkart_taxons, :only => [:index,:flipkart_products]
    get 'flipkart_taxons/flipkart_products'
    get 'flipkart_products/search_products'

  end
  # get "/admin/flipkart_taxons/products_by_taxons","flipkart_taxons#products_by_taxons",:as=>'flipkart_products_by_taxons'

end

app/controllers/spree/admin/flipkart_products_controller.rb
class Spree::Admin::FlipkartProductsController < Spree::Admin::BaseController

  def create
    if @product = Spree::Flipkart::Product.find_and_save_to_spree(params[:asin],params[:cache_pams])
      redirect_to edit_admin_product_path(@product)
    else
      redirect_to admin_amazon_products_path
    end
  end

  def index
    @searcher = Spree::Core::Search::Flipkart.new(params)
    p "==============searrararaa================"
    p @searcher
    p "=========================count===="
    p @searcher.retrieve_products.count
    p "-------------------djhdjjdjdjd"
    @amazon_products = @searcher.retrieve_products
  end

  def search_products
    # @searcher = Spree::Core::Search::Flipkart.new(params)
    # p "==============searrararaa================"
    # p @searcher
    # p "=========================count===="
    # p @searcher.retrieve_products.count
    # p "-------------------djhdjjdjdjd"
    # @amazon_products = @searcher.retrieve_products
    #
    # fk_api = FlipkartApi.new('shivar547', 'f26474f2297943c2a72e91cb91fb3770', "v1.1.0")
    # @categories = fk_api.get_categories(json)
    @flipkart_products,@cache = Spree::Flipkart::Product.search_prod(params["keywords"])

  end

  def flipkart_products
    fk_api = FlipkartApi.new('shivar547', 'f26474f2297943c2a72e91cb91fb3770', "v1.1.0")
    @categories = fk_api.get_categories(json)
    #
    # @searcher = Spree::Core::Search::Amazon.new(params)
    # p "==============searrararaa================"
    # p @searcher
    # p "=========================count===="
    # p @searcher.retrieve_products.count
    # p "-------------------djhdjjdjdjd"
    # @amazon_products = @searcher.retrieve_products

  end

end

app/views/spree/admin/flipkart_products/index.html.erb
<%= render :partial => 'spree/admin/shared/amazon_sub_menu' %>

<h1><%= t("amazon_products") %></h1>

<table class="index">
  <thead data-hook="admin_amazon_products_index_headers">
    <th><%= t("image") %></th>
    <th><%= t("amazon_id") %></th>
    <th><%= t('price') %></th>
    <th><%= t("name") %></th>
    <th data-hook="admin_amazon_products_index_header_actions">&nbsp;</th>
  </thead>
  <tbody>
    <% @flipkart_products.each do |product|%>
      <tr data-hook="admin_amazon_products_index_rows">
        <td><%= link_to image_tag(product.images.first.attachment.url), amazon_affiliate_url(product.id), :alt => product.name, :target => '_blank' if product.images.first %></td>
        <td><%= product.id %></td>
        <td><%= product.price %></td>
        <td><%= link_to product.name.html_safe, amazon_affiliate_url(product.id), :target => '_blank' %></td>
        <td><%= button_to t(:add_to_store), admin_amazon_products_path(:asin => product.id), :method => 'POST' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @amazon_products %>

<%= render :partial => 'spree/admin/shared/flipkart_product_search' %>

app/views/spree/admin/flipkart_products/search_products.html.erb
<%= render :partial => 'spree/admin/shared/amazon_sub_menu' %>

<h1><%= t("flipkart_products") %></h1>

<table class="index">
  <thead data-hook="admin_amazon_products_index_headers">
  <th><%= t("image") %></th>
  <th><%= t("amazon_id") %></th>
  <th><%= t('price') %></th>
  <th><%= t("name") %></th>
  <th data-hook="admin_amazon_products_index_header_actions">&nbsp;</th>
  </thead>
  <tbody>
  <% @flipkart_products.each do |product|%>
    <tr data-hook="admin_amazon_products_index_rows">
      <td><%= link_to image_tag(product.images.first.attachment.url), product.product_url, :alt => product.name, :target => '_blank' if product.images.first %></td>
      <td><%= product.id %></td>
      <td><%= product.price %></td>
      <td><%= link_to product.name.html_safe, product.product_url, :target => '_blank' %></td>
      <td><%= button_to t(:add_to_store), admin_flipkart_products_path(:asin => product.id,:cache_pams=>@cache), :method => 'POST' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%#= paginate @amazon_products %>

<%= render :partial => 'spree/admin/shared/flipkart_product_search' %>