config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :amazon_products, :only => [:create, :index]
    resources :amazon_imports, :only => [:create, :index, :new]
    resources :amazon_taxons, :only => [:index]

    resources :flipkart_products, :only => [:create, :index]
    resources :flipkart_imports, :only => [:create, :index, :new]
    resources :flipkart_taxons, :only => [:index,:flipkart_products]
    get 'flipkart_taxons/flipkart_products'
    get 'flipkart_products/search_products'

  end
  # get "/admin/flipkart_taxons/products_by_taxons","flipkart_taxons#products_by_taxons",:as=>'flipkart_products_by_taxons'

end

app/controllers/spree/admin/flipkart_imports_controller.rb
class Spree::Admin::FlipkartImportsController < Spree::Admin::BaseController

  def create
    if defined? Delayed::Job
      csv = Spree::Amazon::Import.new(:attachment => params[:upload_file])
      csv.save!
      Spree::Amazon::Import.delay.run(csv.attachment.expiring_url(36000), import_id: csv.id)
    else
      Spree::Amazon::Import.run(params[:upload_file].path)
    end
    redirect_to admin_amazon_imports_path, :notice => t(:upload_complete)
  end

  def index
  end

  def new
    send_data File.read(File.expand_path('../../../../assets/templates/Amazon Import Template.csv', __FILE__)), :filename => t(:amazon_import_template) + '.csv'
  end

end

app/views/spree/admin/flipkart_imports/index.html.erb
<%= render :partial => 'spree/admin/shared/amazon_sub_menu' %>

<h1><%= t("amazon_imports") %></h1>
<p><%= t(:import_instructions) %></p>
<p><%= link_to t(:download_template), new_admin_amazon_import_path %></p>
<h2><%= t(:upload_spreadsheet) %></h2>
<p>
  <%= form_tag admin_amazon_imports_path, :method => :post, :multipart => true do |f| %>
    <p><%= file_field_tag :upload_file %></p>
    <p><%= button t(:upload) %></p>
  <% end %>
</p>