config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :amazon_products, :only => [:create, :index]
    resources :amazon_imports, :only => [:create, :index, :new]
    resources :amazon_taxons, :only => [:index]

    resources :flipkart_products, :only => [:create, :index]
    resources :flipkart_imports, :only => [:create, :index, :new]
    resources :flipkart_taxons, :only => [:index,:flipkart_products]
    get 'flipkart_taxons/flipkart_products'
    get 'flipkart_products/search_products'

  end
  # get "/admin/flipkart_taxons/products_by_taxons","flipkart_taxons#products_by_taxons",:as=>'flipkart_products_by_taxons'

end

app/controllers/spree/admin/amazon_taxons_controller.rb
class Spree::Admin::AmazonTaxonsController < Spree::Admin::BaseController

  def index
    if params[:taxon_id]
      @taxons = Spree::Amazon::Taxon.find(params[:taxon_id]).children
    else
      @taxons = Spree::Amazon::Taxon.roots
    end
  end

end

app/views/spree/admin/amazon_taxons/index.html.erb
<%= render :partial => 'spree/admin/shared/amazon_sub_menu' %>

<h1><%= t("amazon_taxons") %></h1>

<table class="index">
  <thead data-hook="admin_amazon_index_headers">
    <th><%= t("name") %></th>
    <th data-hook="admin_amazon_index_header_actions">&nbsp;</th>
  </thead>
  <tbody>
    <% @taxons.each do |taxon|%>
      <tr data-hook="admin_amazon_index_rows">
        <td><%= taxon.name %></td>
        <td>
          <%= link_to t(:child_taxons), admin_amazon_taxons_path(:taxon_id => taxon.id) %>
          |
          <%= link_to t(:view_products), admin_amazon_products_path(:taxon_id => taxon.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render :partial => 'spree/admin/shared/amazon_product_search' %>